format = """
[](#cba6f7)\
$os\
$username\
[](bg:#45475a fg:#cba6f7)\
$directory\
[](fg:#45475a bg:#f38ba8)\
$git_branch\
$git_status\
[](fg:#f38ba8 bg:#fab387)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#fab387 bg:#89b4fa)\
$docker_context\
[](fg:#89b4fa)\
\n$character"""

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 2000

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#11111b bg:#cba6f7"
style_root = "fg:#11111B bg:#cba6f7"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#45475a"
disabled = true # Disabled by default

[directory]
style = "bg:#45475a fg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[character]
success_symbol = "[❯](#a6e3a1)"
error_symbol = "[❯](#f38ba8)"
vimcmd_symbol = "[❮](#cba6f7)"

[c]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#11111b bg:#89b4fa"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#11111b bg:#f38ba8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#11111b bg:#f38ba8"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#11111b bg:#fab387"
format = '[ $symbol ($version) ]($style)'

#[time]
#disabled = true
#time_format = "%R" # Hour:Minute Format
#style = "bg:#cba6f7"
#format = '[ ♥ $time ]($style)'
